# Generated by Django 3.1.13 on 2021-11-27 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20211127_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='img',
            new_name='image',
        ),
    ]
