# Generated by Django 3.1.13 on 2021-11-27 05:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20211127_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text_full',
            field=ckeditor.fields.RichTextField(verbose_name="To'liq matni"),
        ),
    ]
