# Generated by Django 3.1.13 on 2021-11-29 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20211127_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='body',
        ),
    ]
