# Generated by Django 3.1.13 on 2021-12-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20211129_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
