# Generated by Django 3.1.13 on 2021-12-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_remove_customuser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customimage',
            name='image',
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users_img', verbose_name='Rasm:'),
        ),
    ]
