# Generated by Django 3.1.13 on 2021-11-23 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guruh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guruh', models.CharField(max_length=80, verbose_name='Guruh')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100, verbose_name='F.I.O')),
                ('guruh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.guruh')),
            ],
        ),
    ]
