# Generated by Django 3.1.13 on 2021-11-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='natija',
            field=models.ImageField(upload_to='images'),
        ),
    ]
