# Generated by Django 3.1.13 on 2021-11-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20211124_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='natija',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
