# Generated by Django 3.1.13 on 2021-11-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20211124_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='natija',
            field=models.TextField(),
        ),
    ]
